import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Headless WP Starter',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        <footer
          style={{ textAlign: 'center', marginTop: '20px', fontSize: '14px' }}
        >
          © 2024 Lindsay Aiello
        </footer>
      </body>
    </html>
  );
}
